server:
  port: 18080
spring:
  application:
    name: spring-ai-alibaba-examples
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.117.3:3306/chat_memory?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456